changelog:
- type: DEPENDENCY_BUMP
  dependencyOwner: solo-io
  dependencyRepo: go-utils
  dependencyTag: v0.11.5
  description: Update go-utils to version 0.11.5
  issueLink: https://github.com/solo-io/gloo/issues/1998
- type: NON_USER_FACING
  description: Upgrade the stats server version to DRY out start up config
  issueLink: https://github.com/solo-io/gloo/issues/1998
