changelog:
  - type: HELM
    description: >
      Ensure that all stats server settings are consistent across open source and enterprise Gloo
      by moving the enabled logic into a global helper template. This change introduces a global
      value that all deployments will use as their default stats server settings:
      `global.glooStats.enabled`. This value can be overridden by an individual deployment by
      setting a field on that deployment. For example, to disable stats on discovery, you can do
      `discovery.deployment.stats.enabled=false`. Note that this change has converted the `stats`
      field on our deployment objects from a boolean to an object with an `enabled` boolean field
      inside of it.
    issueLink: https://github.com/solo-io/gloo/issues/1884
