apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    gloo: proxycontroller
  name: proxycontroller
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      gloo: proxycontroller
  template:
    metadata:
      labels:
        gloo: proxycontroller
    spec:
      serviceAccountName: proxycontroller
      containers:
        - image: quay.io/solo-io/proxycontroller:1.2.12
          imagePullPolicy: IfNotPresent
          name: proxycontroller
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: proxycontroller
rules:
  - apiGroups:
      - "gloo.solo.io"
    resources:
      - proxies
      - upstreams
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: proxycontroller-binding
subjects:
  - kind: ServiceAccount
    name: proxycontroller
    namespace: gloo-system
roleRef:
  kind: ClusterRole
  name: proxycontroller
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxycontroller
  namespace: gloo-system