apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleeper
  template:
    metadata:
      labels:
        app: sleeper
    spec:
      containers:
        - name: sleeper
          image: soloio/sleeper:v0.0.1
          env:
          - name: PORT
            value: "8080"
          ports:
            - containerPort: 8080
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: sleeper
spec:
  selector:
    app: sleeper
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
