changelog:
  - type: FIX
    issueLink: https://github.com/solo-io/gloo/issues/7807
    description: Expose `config.core.v3.Cluster.SlowStartConfig` for `RoundRobin` and `LeastRequest` load balancers. Requires CRD update to be able to use.