changelog:
  - type: FIX
    issueLink: https://github.com/solo-io/gloo/issues/1777
    description: >
      Fix a crash in Gloo that occurs when no kubeconfig is present
       (which is expected in non-Kubernetes environments).