changelog:
- type: NON_USER_FACING
  description: Process custom Ext Auth configuration on virtual hosts, routes, and weighted destinations.
  issueLink: https://github.com/solo-io/gloo/issues/1396
  resolvesIssue: false